### ISSUE TITLE
NUCLE like edits

### ISSUE THREAD

**Issue by sai-prasanna** [snukky/wikiedits#2]
The paper mentions +Select corpus which filters only edits that are like those that appear in NUCLE corpus. Any script available to do that?

**Comment by snukky** [comment]
A similar script for filtering sentences by error patterns can be found here: https://github.com/snukky/gec-scripts/tree/master/patterns. Better late than never.

**Comment by sai-prasanna** [comment]
@snukky  Thanks, it was a fellow colleague who contacted you :D .
btw, Are there any other datasets for GEC other than NUCLE, Lang-8? 
I found a current paper mentioning a 'extended Lang-8 dataset' , I guess they crawled from the site.

**Comment by snukky** [comment]
There is also the CLC FCE data set, which is a publicly available part of the CLC corpus, and it's smaller than NUCLE. So mostly for testing purposes, like JFLEG. The AESW shared task provided data in scientific domain.

Lang-8 has several versions, and I think all larger than ca. 2.2M sentences contain additionally crawled examples.
