### ISSUE TITLE
txt_edits.py file can't handle large text files

### ISSUE THREAD

**Issue by gurunath-p** [snukky/wikiedits#3]
1. In bin/txt_edits.py, the text in input and output text files are being read as a whole in the lines
 `old_text = " ".join(line.rstrip() for line in file.readlines())` and 
`new_text = " ".join(line.rstrip() for line in file.readlines())` 
which doesn't work for large files(such as datasets, whose size is in GBs).

2. Also in setup.py, the line has to be corrected from 
`long_description=open('README.txt').read(),` to
`long_description=open('README.md').read(),`

**Comment by snukky** [comment]
Many thanks for reporting these. I think I've never been using `txt_edits.py` for real applications, only for testing.

Have you fixed them and are you going to make a pull request? Both are easy to fix.

**Comment by gurunath-p** [comment]
I think this PR #4  would fix this. Please check
